### ISSUE TITLE
引号未闭合，这个怎么关掉

### ISSUE THREAD

**Issue by ygqygq2** [Jinjiang/zhlint#107]
[zhlint] 引号未闭合

**Comment by Jinjiang** [comment]
我看了一下你引用的这个 issue，感觉重点是回避检查代码片段，不然代码里肯定有很多非中文的书写习惯会导致错误，目前 zhlint 默认只会跳过一些比较明显的非中文内容，比如 markdown 里的 code block。

**Comment by Jinjiang** [comment]
针对你提供的用例，我建议在执行 zhlint 的上层环境加一些判断规则吧。如果想完全跳过 zhlint 的所有检查，可以加 `<!-- zhlint disabled -->`，但我不确定这是不是你想要的。

**Comment by ygqygq2** [comment]
感觉作者开发这么好用的工具，规范主要还是用于注释中和 markdown 这种书写。代码和配置文件内容的话，因为各种符号和编程规范，确实可能会冲突。我现在的配置是这样，写前端、JS、TS 这些用起来没啥问题。注释的代码这个引号的提示问题，是 eslint-plugin-zhlint 这个工具没有处理好。

```
        zhlint: {
          rules: {
            halfWidthPunctuation: '',
            fullWidthPunctuation: '',
            unifiedPunctuation: 'simplified',
            spaceBetweenHalfWidthLetters: false,
            spaceAfterHalfWidthPunctuation: false,
          },
        },
```
