### ISSUE TITLE
请教关于 .zhlintrc 的使用问题

### ISSUE THREAD

**Issue by salvatore-w** [Jinjiang/zhlint#109]
您好，

因为有相应需求，所以需要修改部分配置，按照文档的说明我进行了如下步骤：
 
1. 创建 `.zhlintrc` 文件，内容为：

```
{
  "preset": "default",
  "rules": {
    "unifiedPunctuation": "traditional",
    "spaceOutsideHalfQuote": false,
    "halfWidthPunctuation": "（）"
  }
}
```

2. 执行 `zhlint --config /Users/xxx/Documents/xxxx/.zhlintrc.json`，尚未提示任何配置相关情况。

3. 执行 `zhlint /Users/Documents/xxxx/xx.md`，输出的结果与最开始一模一样，并没有按照配置要求。

我尝试过的其他方案：

1. `zhlint --dir /Documents/xxxx/` 后执行 `zhlint --config .zhlintrc.json`
2. `cd Users/xxx/Documents/xxxx/`  后执行 `zhlint --config`
3. `cd Users/xxx/Documents/xxxx/`  后执行 `zhlint --config .zhlintrc.json`

想请问正确的使用方法是什么？我在使用过程中出现了什么错误？

**Comment by Jinjiang** [comment]
```
zhlint /Users/.../input.md --output ./output.md --config .zhlintrc.json
```

应该没有问题

**Comment by Jinjiang** [comment]
如果你想直接在源文件上修复，需要加 `--fix` 参数
