### ISSUE TITLE
全中文下，圆括号用半角还是全角？

### ISSUE THREAD

**Issue by cool8jay** [Jinjiang/zhlint#119]
测试了一下，目前zhlint建议用半角圆括号。
个人建议用全角。

**Comment by Jinjiang** [comment]
是的，默认是半角括号。默认配置来自之前的中英文技术文档维护经验和约定，实际使用时可以根据个人习惯自定义配置。具体见 README

> Almost the rules come from the past translation experiences in [W3C HTML Chinese interest group](https://www.w3.org/html/ig/zh/wiki/Main_Page) and [Vue.js Chinese docsite](https://github.com/vuejs/cn.vuejs.org/wiki).
