### ISSUE TITLE
圆括号匹配问题

### ISSUE THREAD

**Issue by TechQuery** [Jinjiang/zhlint#18]
我在配置 https://github.com/freeCodeCamp/news-translation **Lint Action** 时遇到很多如下报错：

> Unmatched closed bracket ) at xxx

发现报错附近一定有 **ASCII 表情**（如 `;-)`）或**二级数字列表号**（如 `1)`）等**英语习惯用法**，这会让**英译中工作者**非常抓狂……

**Comment by Jinjiang** [comment]
可以用 `ignoredCases` 临时绕过去吗？我之前印象中也遇到过

**Comment by TechQuery** [comment]
我没试，文件太多了，一篇文章都可能卡很多次，排查了十几篇我就放弃了，暂时转 https://github.com/lint-md/lint-md 了……

**Comment by Jinjiang** [comment]
明白了，我会具体看一下。抱歉目前这个工具还不够好用

**Comment by Jinjiang** [comment]
@TechQuery 现在最新版本的 lint 过程不会因为未匹配的括号而中断，但仍然会有一个 warning，如果仍有兴趣的话可以尝试一下。再下个版本我会考虑加一个选项忽略这类 warning 增强使用体验。谢谢。

**Comment by Jinjiang** [comment]
#82 下个版本会增加一个 `noSinglePair` 选项，默认为 `true`，可以选择关掉。
