### ISSUE TITLE
ReferenceError: invalidFiles is not defined

### ISSUE THREAD

**Issue by Rabbitzzc** [Jinjiang/zhlint#24]
```sh
yarn global add zhlint
```

然后在测试运行某个文件的时候：
```sh
zhlint ./test/hh.md
```
出现报错： `ReferenceError: invalidFiles is not defined`

--- 补充 ---
看了一下应该是 [#L72](https://github.com/Jinjiang/zhlint/blob/v0.3.0/src/logger.js#L72) 出现了问题，参数没有定义，建议加上 `eslint` 工具

**Comment by veaba** [comment]
全局升级一下你的 zhlint 版本到最新 ·0.3.0·，我本地的 `zhlint@0.2.2`，也是有这个问题。

升级后解决了。

**Comment by Psilocine** [comment]
升级到 v0.3 并没有解决楼主的错误，还是会报，而且 fix/output 命令也失效了! 😭
[image](https://user-images.githubusercontent.com/25545052/142114227-c6f0e9a8-377a-4c4d-9514-43cfba941ab7.png)

**Comment by Jinjiang** [comment]
这个问题现在还能重现吗？我最近用 TS 重构了一下，版本号升级到了 v0.5.0，这个问题应该已经修复了。
如果还会遇到这个问题，可以 reopen，我这里先关掉了。

其它问题可以另外开 issue 讨论。

谢谢
